package com.imaviso.stash.ui.theme

import androidx.compose.ui.graphics.Color

// Stash brand palette (indigo primary, muted slate secondary).
// Used as the Material 3 fallback when dynamic color is unavailable.

// Light scheme
val BrandPrimary = Color(0xFF4659E2)
val BrandOnPrimary = Color(0xFFFFFFFF)
val BrandPrimaryContainer = Color(0xFFE0E0FF)
val BrandOnPrimaryContainer = Color(0xFF00006E)
val BrandSecondary = Color(0xFF5C5D72)
val BrandOnSecondary = Color(0xFFFFFFFF)
val BrandSecondaryContainer = Color(0xFFE1E0F9)
val BrandOnSecondaryContainer = Color(0xFF191A2C)
val BrandTertiary = Color(0xFF78536C)
val BrandOnTertiary = Color(0xFFFFFFFF)
val BrandTertiaryContainer = Color(0xFFFFD8EE)
val BrandOnTertiaryContainer = Color(0xFF2E1126)
val BrandError = Color(0xFFBA1A1A)
val BrandErrorContainer = Color(0xFFFFDAD6)
val BrandOnError = Color(0xFFFFFFFF)
val BrandOnErrorContainer = Color(0xFF410002)
val BrandBackground = Color(0xFFFDF8FF)
val BrandOnBackground = Color(0xFF1B1B21)
val BrandSurface = Color(0xFFFDF8FF)
val BrandOnSurface = Color(0xFF1B1B21)
val BrandSurfaceVariant = Color(0xFFE3E1EC)
val BrandOnSurfaceVariant = Color(0xFF46464F)
val BrandOutline = Color(0xFF777680)
val BrandOutlineVariant = Color(0xFFC7C5D0)
val BrandScrim = Color(0xFF000000)

// Dark scheme
val BrandPrimaryDark = Color(0xFFBEC2FF)
val BrandOnPrimaryDark = Color(0xFF14138E)
val BrandPrimaryContainerDark = Color(0xFF2A33C9)
val BrandOnPrimaryContainerDark = Color(0xFFE0E0FF)
val BrandSecondaryDark = Color(0xFFC5C4DD)
val BrandOnSecondaryDark = Color(0xFF2D2F42)
val BrandSecondaryContainerDark = Color(0xFF444559)
val BrandOnSecondaryContainerDark = Color(0xFFE1E0F9)
val BrandTertiaryDark = Color(0xFFE6B6CE)
val BrandOnTertiaryDark = Color(0xFF46263B)
val BrandTertiaryContainerDark = Color(0xFF5E3C52)
val BrandOnTertiaryContainerDark = Color(0xFFFFD8EE)
val BrandErrorDark = Color(0xFFFFB4AB)
val BrandErrorContainerDark = Color(0xFF93000A)
val BrandOnErrorDark = Color(0xFF690005)
val BrandOnErrorContainerDark = Color(0xFFFFDAD6)
val BrandBackgroundDark = Color(0xFF121318)
val BrandOnBackgroundDark = Color(0xFFE4E1E9)
val BrandSurfaceDark = Color(0xFF121318)
val BrandOnSurfaceDark = Color(0xFFE4E1E9)
val BrandSurfaceVariantDark = Color(0xFF46464F)
val BrandOnSurfaceVariantDark = Color(0xFFC6C5D0)
val BrandOutlineDark = Color(0xFF90909A)
val BrandOutlineVariantDark = Color(0xFF46464F)
val BrandScrimDark = Color(0xFF000000)
